a.out:hospital_app.o book_appointment.o delete_account.o modify_details.o printmenu.o save_data_file.o print_details.o sync_from_file.o
	cc -c hospital_app.c book_appointment.c delete_account.c modify_details.c printmenu.c save_data_file.c print_details.c sync_from_file.c


